# Generated by Django 5.0.6 on 2024-08-04 19:36

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_clientreview_order_reviewed'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyDiscountCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=8)),
                ('date', models.DateField(default=datetime.date.today)),
                ('used_by', models.ManyToManyField(blank=True, related_name='used_discount_codes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
