# Generated by Django 5.0.6 on 2024-07-30 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_order_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='review_email_sent',
            field=models.BooleanField(default=False),
        ),
    ]
