# Generated by Django 5.0.6 on 2024-08-04 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_dailydiscountcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='CityDeliveryInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100)),
                ('delivery_days', models.PositiveIntegerField()),
                ('delivery_charge', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
