# Generated by Django 5.0.6 on 2024-08-04 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_citydeliveryinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citydeliveryinfo',
            name='delivery_charge',
            field=models.DecimalField(decimal_places=1, max_digits=10),
        ),
    ]
