# Generated by Django 5.0.6 on 2024-08-04 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_citydeliveryinfo_delivery_charge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citydeliveryinfo',
            name='delivery_charge',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
