# Generated by Django 5.0.6 on 2024-08-07 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_citydeliveryinfo_delivery_charge'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_received',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='not_received_click_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='not_received_clicked',
            field=models.BooleanField(default=False),
        ),
    ]
