# Generated by Django 5.0.6 on 2024-08-07 20:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_order_is_received_order_not_received_click_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='review_token_expiry',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 6, 20, 6, 7, 42613, tzinfo=datetime.timezone.utc)),
        ),
    ]
